# https://taskfile.dev/installation/
version: "3"

tasks:
  debug:
    desc: Create debug pod
    cmds:
      - kubectl apply -f dev/debug-pod.yaml
      - kubectl exec -it debugpod -n kube-system -- /bin/sh
  qdebug:
    cmds:
      - kubectl delete -f dev/debug-pod.yaml
