apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute

metadata:
  name: hatchet-caddy-external
  namespace: hatchet
  annotations:
    argocd.argoproj.io/sync-wave: "4"

spec:
  parentRefs:
    - name: external
      namespace: gateway

  hostnames:
    - hatchet.gearhawk.io

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: caddy
          port: 8080
