caddy:
  enabled: true
sharedConfig:
  # you can disable shared config by setting this to false
  enabled: true

  # these are the most commonly configured values
  serverUrl: "http://localhost:8080"
  serverAuthCookieDomain: "localhost:8080" # the domain for the auth cookie
  serverAuthCookieInsecure: "t" # allows cookies to be set over http
  serverAuthSetEmailVerified: "t" # automatically sets email_verified to true for all users
  serverAuthBasicAuthEnabled: "t" # allows login via basic auth (email/password)
  grpcBroadcastAddress: "localhost:7070" # the endpoint for the gRPC server, exposed via the `grpc` service
  grpcInsecure: "true" # allows gRPC to be served over http
  defaultAdminEmail: "admin@example.com" # in exposed/production environments, change this to a valid email
  defaultAdminPassword: "Admin123!!" # in exposed/production environments, change this to a secure password

  # you can set additional environment variables here, which will override any defaults
  # env: {}
  seed:
    defaultAdminEmail: "admin@example.com" # in exposed/production environments, change this to a valid email
    defaultAdminPassword: "Admin123!!" # in exposed/production environments, change this to a secure password
    env:
      ADMIN_NAME: "Admin User"
      DEFAULT_TENANT_NAME: "Default"
      DEFAULT_TENANT_SLUG: "default"
      DEFAULT_TENANT_ID: "707d0855-80ab-4e1f-a156-f1c4546cbf52"
api:
  envFrom:
    - secretRef:
        name: hatchet-shared-config

engine:
  envFrom:
    - secretRef:
        name: hatchet-shared-config
