tunnel: typesense.gearhawk.io
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
loglevel: debug
transport-loglevel: debug
warp-routing:
  enabled: true

ingress:
  # https://ryan-schachte.com/blog/cf_tunnel_tcp/
  # - hostname: cnpg.gearhawk.io
  #   service: tcp://postgres-cluster-rw.cnpg-database.svc.cluster.local:5432
  - hostname: proxmox.gearhawk.io
    service: https://cilium-gateway-tls-passthrough.gateway.svc.cluster.local:443
    originRequest:
      originServerName: proxmox.gearhawk.io
  - hostname: "gearhawk.io"
    service: https://cilium-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "gearhawk.io"
      noTLSVerify: true # No valid cert during testing
  - hostname: "*.gearhawk.io"
    service: https://cilium-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "*.gearhawk.io"
      noTLSVerify: true # No valid cert during testing
  - service: http_status:404
