apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    namespace: cloudflared
    files:
      - config.yaml

resources:
  - daemonset.yaml
  - ns.yaml
  - tunnel-credentials.yaml
  - httpbin.yaml
