apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-gearhawk
  namespace: gateway
spec:
  dnsNames:
    - "*.gearhawk.io"
    - "gearhawk.io"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-gearhawk
  usages:
    - digital signature
    - key encipherment
