apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.50.67
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.gearhawk.io"
      tls:
        certificateRefs:
          - name: cert-gearhawk
            kind: Secret
            # group: "" # required
      allowedRoutes:
        namespaces:
          from: All
