apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: gearhawk-hono
      protocol: HTTP
      port: 80
      hostname: "api.gearhawk.io"
      allowedRoutes:
        namespaces:
          from: All
    - name: typesense
      protocol: HTTPS
      port: 443
      hostname: "typesense.gearhawk.io"
      tls:
        certificateRefs:
          - name: cert-gearhawk
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
