apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: gearhawk-hono
      protocol: HTTP
      port: 80
      hostname: api.gearhawk.io
      allowedRoutes:
        namespaces:
          from: All
    - name: healthchecks
      protocol: HTTP
      port: 80
      hostname: healthchecks.gearhawk.io
      allowedRoutes:
        namespaces:
          from: All
    - name: typesense
      protocol: HTTP
      port: 80
      hostname: typesense.gearhawk.io
      allowedRoutes:
        namespaces:
          from: All
