apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gpu
  namespace: argocd
  labels:
    gearhawk.lab: gpu
spec:
  generators:
    - git:
        repoURL: https://github.com/wtp43/gearhawk-lab
        revision: HEAD
        directories:
          - path: k8s/infra/gpu/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        gearhawk.lab: gpu
    spec:
      project: gpu
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/wtp43/gearhawk-lab
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
