apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gpu
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/wtp43/gearhawk-lab"
    - https://nvidia.github.io/k8s-device-plugin
    - https://nvidia.github.io/dcgm-exporter/helm-charts
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "kube-system"
      server: "*"
    - namespace: "monitoring"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
