# issue: https://github.com/longhorn/longhorn/issues/4853
preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
  jobEnabled: false
persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultMkfsParams: ""
  defaultClassReplicaCount: 1
defaultNodeSelector:
  enable: false # disable by default
  selector: []

defaultSettings:
  createDefaultDiskLabeledNodes: true
