# https://taskfile.dev/installation/
version: "3"

tasks:
  init:
    desc: Initialize the dev project
    cmds:
      - terragrunt init -upgrade

  plan:
    desc: Plan the dev cluster
    cmds:
      - terragrunt plan

  create:
    desc: Create the dev cluster
    cmds:
      - terragrunt apply -auto-approve
      - 'echo "Dev kubeconfig:  export KUBECONFIG=$(pwd)/output/kube-config.yaml"'
      - 'echo "Dev talosconfig: talosctl --talosconfig $(pwd)/output/talos-config.yaml -e 192.168.50.86 -n 192.168.50.86,192.168.50.87,192.168.50.88 ..."'

  destroy:
    desc: Destroy the dev cluster
    cmds:
      - terragrunt destroy -auto-approve

  recreate:
    desc: Recreate the dev cluster
    cmds:
      - task destroy
      - task create
