# https://taskfile.dev/installation/
version: "3"

tasks:
  init:
    desc: Initialize the project
    cmds:
      - terraform init -upgrade
      # - go mod download

  create:
    desc: Create the cluster
    cmds:
      - terraform apply -auto-approve
      - ./get_talos_kubernetes_config.sh
      - ./post-bootstrap/patch-user-volume.sh

  destroy:
    desc: Destroy the cluster
    cmds:
      # - terraform destroy -target=null_resource.terraform-up -auto-approve
      - terraform destroy -auto-approve

  recreate:
    desc: Recreate the cluster
    cmds:
      - task destroy
      - task create
      # - task argocd
  patch-work:
    desc: Create the cluster
    cmds:
      - talosctl apply-config -n 192.168.50.110 -f ./output/talos-machine-config-work-00.yaml
      - talosctl apply-config -n 192.168.50.111 -f ./output/talos-machine-config-work-01.yaml
      - talosctl apply-config -n 192.168.50.112 -f ./output/talos-machine-config-work-02.yaml
      - talosctl apply-config -n 192.168.50.114 -f ./output/talos-machine-config-work-04.yaml
  patch-vol:
    desc: Patch user volumes
    cmds:
      - ./post-bootstrap/patch-user-volume.sh
