# https://taskfile.dev/installation/
version: "3"

tasks:
  init:
    desc: Initialize the project
    cmds:
      - terraform init -upgrade
      # - go mod download

  create:
    desc: Create the cluster
    cmds:
      - terraform apply -auto-approve
      - ./get_talos_kubernetes_config.sh
      # - ./post-bootstrap/patch-user-volume.sh

  destroy:
    desc: Destroy the cluster
    cmds:
      # - terraform destroy -target=null_resource.terraform-up -auto-approve
      - terraform destroy -auto-approve

  recreate:
    desc: Recreate the cluster
    cmds:
      - task destroy
      - task create
      # - task argocd
  patch:
    desc: Patch all nodes
    cmds:
      - talosctl apply-config -n 192.168.50.110 -f ./output/talos-machine-config-work-00.yaml
      # - talosctl apply-config -n 192.168.50.111 -f ./output/talos-machine-config-work-01.yaml
      - talosctl apply-config -n 192.168.50.112 -f ./output/talos-machine-config-work-02.yaml
      - talosctl apply-config -n 192.168.50.114 -f ./output/talos-machine-config-work-04.yaml
      - talosctl apply-config -n 192.168.50.115 -f ./output/talos-machine-config-work-05.yaml
      - talosctl apply-config -n 192.168.50.116 -f ./output/talos-machine-config-work-06.yaml
      - talosctl apply-config -n 192.168.50.100 -f ./output/talos-machine-config-ctrl-00.yaml
      # - talosctl apply-config -n 192.168.50.101 -f ./output/talos-machine-config-ctrl-01.yaml
      - talosctl apply-config -n 192.168.50.102 -f ./output/talos-machine-config-ctrl-02.yaml
      - talosctl apply-config -n 192.168.50.104 -f ./output/talos-machine-config-ctrl-04.yaml
      - talosctl apply-config -n 192.168.50.105 -f ./output/talos-machine-config-ctrl-05.yaml
      - talosctl apply-config -n 192.168.50.106 -f ./output/talos-machine-config-ctrl-06.yaml
  patch-vol:
    desc: Patch user volumes
    cmds:
      - ./post-bootstrap/patch-user-volume.sh

  patch-gpu-worker:
    desc: Patch talos with nvidia drivers
    cmds:
      - talosctl patch mc --patch @talos/patches/gpu-worker-patch.yaml -n 192.168.50.110
