kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: no-replicas
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # volumeBindingMode is immutable, so changing it requires delete+recreate.
    argocd.argoproj.io/sync-options: Force=true,Replace=true
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes, determines when Lonhorn will cleanup an error replica
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local"
