apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-openai

resources:
  - ns.yaml
  - secrets.yaml
  - vllm-openai-pvc.yaml
  - deployment.yaml
  - vllm-openai-svc.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: vllm-openai
      app.kubernetes.io/component: inference
      app.kubernetes.io/instance: vllm-openai
