apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-secret
  namespace: api-gearhawk
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-config"
type: kubernetes.io/dockerconfigjson
