apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: gpu
  sources:
    - repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
      chart: dcgm-exporter
      targetRevision: 4.8.3
      helm:
        values: |
          runtimeClassName: nvidia
          nodeSelector:
            kubernetes.io/hostname: work-00
          serviceMonitor:
            enabled: false
    - repoURL: https://github.com/wtp43/gearhawk-lab
      targetRevision: HEAD
      ref: values

  destination:
    name: in-cluster
    namespace: monitoring

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
