apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external
  namespace: argocd
  labels:
    gearhawk.lab: external
spec:
  generators:
    - git:
        repoURL: https://github.com/wtp43/gearhawk-lab
        revision: HEAD
        directories:
          - path: k8s/apps/external/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        gearhawk.lab: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: external
      source:
        repoURL: https://github.com/wtp43/gearhawk-lab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
