apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs-container
          image: wjt40398/gearhawk:app
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 2
              memory: 2Gi
            limits:
              cpu: 8
              memory: 12Gi
      imagePullSecrets:
        - name: docker-secret
