apiVersion: v1
kind: Service
metadata:
  name: nextjs-svc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: nextjs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
