apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-classification

resources:
  - ns.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: vllm-classification
      app.kubernetes.io/component: inference
      app.kubernetes.io/instance: vllm-classification

configMapGenerator:
  - name: vllm-classification-app
    files:
      - server.py
