apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-classification-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: no-replicas
  volumeMode: Filesystem
