apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      gearhawk.lab: controllers
      app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
