apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lmstudio

resources:
  - ns.yaml
  - secrets.yaml
  - lmstudio-pvc.yaml
  - deployment.yaml
  - lmstudio-svc.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: lmstudio
      app.kubernetes.io/component: inference
      app.kubernetes.io/instance: lmstudio
