apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthchecks

resources:
  - ns.yaml
  - healthchecks-secret-key.yaml
  - healthchecks-db-secret.yaml
  - deployment.yaml
  - internal-route.yaml
  - external-route.yaml
  - smtp-secret.yaml
