apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: docker-secret
  namespace: gearhawk-website
spec:
  itemPath: "vaults/gearhawk-k8s/items/docker-config"
type: kubernetes.io/dockerconfigjson
