apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - typesense-apikey.yaml
  - crd.yaml
  - ns.yaml
  - rbac.yaml
  - operator.yaml
  - operator-config.yaml
  - external-route.yaml
  - internal-route.yaml
