# Configuration of Typesense fed to the operator goes here
apiVersion: typesenseproject.org/v1
kind: TypesenseOperator
metadata:
  name: type-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 2
  namespace: typesense
  image: typesense/typesense:28.0
  env:
    - name: APIKEY
      valueFrom:
        secretKeyRef:
          name: typesense-apikey
          key: apikey
  resources:
    requests:
      memory: 1Gi
      cpu: 2
      ephemeral-storage: "1Gi"

    limits:
      memory: 8Gi
      cpu: 6
      ephemeral-storage: "4Gi"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - work-00
                  - work-01
  # topologySpreadConstraints:
  #   - labelSelector:
  #       matchLabels:
  #         app: typesense
  #     maxSkew: 1
  #     topologyKey: kubernetes.io/hostname
  #     whenUnsatisfiable: DoNotSchedule
  # storageClass:
  #   name: standard
  #   size: "100Mi"
  # startupProbe:
  #  failureThreshold: 10
  #  periodSeconds: 10
  # livenessProbe:
  #  failureThreshold: 2
  #  periodSeconds: 10
config:
  # Name of the secret
  secret: "typesense-apikey"
  # Define all environment variables here.
  # NOTE: This will add / override existing env variables defined as default for the operator
  env:
    TYPESENSE_ENABLE_CORS: "true"
