apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gearhawk-postgres-user
  namespace: gearhawk-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/gearhawk-postgres-user"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gearhawk-pipeline-worker
  namespace: gearhawk-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/gearhawk-pipeline-worker"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gearhawk-postgres-superuser
  namespace: gearhawk-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/gearhawk-postgres-superuser"
