apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: solidtime-owner
  namespace: solidtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/gearhawk-k8s/items/solidtime-owner"
type: kubernetes.io/basic-auth
