apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2-store
  namespace: cnpg-hatchet
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
      - name: AWS_DEFAULT_REGION
        value: auto
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: https://ef958561965cfffa26ef01e72a2432ca.r2.cloudflarestorage.com
    s3Credentials:
      accessKeyId:
        name: r2-creds
        key: access-key-id
      secretAccessKey:
        name: r2-creds
        key: secret-access-key
    wal:
      compression: gzip
      maxParallel: 8
    data:
      compression: gzip
      immediateCheckpoint: true
      jobs: 2
  retentionPolicy: "7d"
