apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gearhawk-postgres-superuser
  namespace: cnpg-hatchet
  labels:
    cnpg.io/reload: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/gearhawk-postgres-superuser"
type: kubernetes.io/basic-auth
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hatchet-user
  namespace: cnpg-hatchet
  labels:
    cnpg.io/reload: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  itemPath: "vaults/gearhawk-k8s/items/hatchet-user"
type: kubernetes.io/basic-auth
