apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - application-set.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: argocd
      gearhawk.lab: app-management
