global:
  cloud: others
  clusterName: talos
  deploymentEnvironment: production
otelCollectorEndpoint: "signoz-otel-collector.signoz.svc.cluster.local:4317"
otelInsecure: true
presets:
  kubernetesAttributes:
    enabled: true
    # presets.kubernetesAttributes.passthrough -- If true, agents will not make k8s API calls, do discovery, or extract metadata.
    passthrough: false
  hostMetrics:
    enabled: true
    collectionInterval: 30s
  clusterMetrics:
    enabled: true
    collectionInterval: 30s
  k8sEvents:
    enabled: true
    namespaces: [] #
  otlpExporter:
    enabled: true
  logsCollection:
    enabled: true
    blacklist:
      enabled: true
      namespaces:
        - kube-system
  kubeletMetrics:
    enabled: true
    insecureSkipVerify: false
    collectionInterval: 30s
