apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  # - signoz.yaml
  # - external-route.yaml

helmCharts:
  - name: signoz
    repo: https://charts.signoz.io
    includeCRDs: true
    namespace: signoz
    version: 0.101.0
    releaseName: signoz
    valuesFile: ./values.yaml
