apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://charts.signoz.io
      chart: signoz
      targetRevision: 0.101.0
      helm:
        valueFiles:
          - $values/k8s/infra/monitoring/signoz/signoz-values.yaml
    - repoURL: https://github.com/wtp43/gearhawk-lab
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: signoz
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
    #   - ApplyOutOfSyncOnly=true
    # - ServerSideApply=true
